name: Deploy to GitHub Pages

on:
  # `main` ブランチにプッシュするたびにワークフローを実行します
  # 異なるブランチ名を使用する場合は、`main` をブランチ名に置き換えてください
  push:
    branches: [main]
  # このワークフローを GitHub の Actions タブから手動で実行できるようにします。
  workflow_dispatch:

# このジョブがリポジトリをクローンし、ページデプロイメントを作成することを許可します。
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install pnpm
        uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3
      - name: Install, build, and upload your site
        uses: withastro/action@44706356b4eb735f8b9035699eb4796241a040c4 # v6.1.0
        with:
        # path: . # リポジトリ内のAstroプロジェクトのルートロケーション。(オプション)
          node-version: 22 # サイト構築に使用するNodeのバージョン。デフォルトは18です。（オプション）
        # package-manager: pnpm@latest # 依存関係のインストールとサイトのビルドに使用する Node パッケージマネージャ。ロックファイルに基づいて自動的に検出されます。(オプション)

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
